### ISSUE TITLE
add a contact page/email address

### ISSUE THREAD

**Issue by silky** [FixPlanet/FixPlanet.github.io#5]
i guess we need some kind of email contact details?

i'm slightly reluctant to set up email via google, just because it costs money and is a bit un-necessary

maybe we could have a mailing list? or even simply just a general gmail email that is forwarded to a few people? thoughts?

**Comment by marcosh** [comment]
would a free [proton mail](https://proton.me/pricing) account suffice?

**Comment by silky** [comment]
@marcosh yep that sounds good

**Comment by silky** [comment]
done; i made fixplanetclub@protonmail.com

**Comment by silky** [comment]
maybe we can add the password as a secret into the `org` repo somehow.

**Comment by marcosh** [comment]
should we forward mail? Or share the password? Or share somehow a password manager account?

**Comment by silky** [comment]
i'm not totally sure

forwarding might work; but it might be confusing as to who should respond, if it ends up going to all the committee members, say.

maybe for now i'll just work out how to put the password in the `org` repo, and we can deal with it as it comes ...

**Comment by marcosh** [comment]
I would recommend setting up a password manager, since we're probably going to have several passwords flying around
